nav:
    resource: "@NavCMSBundle/Resources/config/routing.yml"
    prefix:   /

nav_cms:
    resource: "@NavCMSBundle/Resources/config/routing/navigation.yml"
    prefix:   /cms

# Homepage
nav_cms_homepage:
    path:     /
    defaults: { _controller: NavCMSBundle:Default:index }

# Display a Page
nav_cms_page_display:
    path: /page/{id}
    defaults: { _controller: NavCMSBundle:Default:display }
