nav_send_grid:
    resource: "@NavSendGridBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

nav:
    resource: "@NavCMSBundle/Resources/config/routing.yml"
    prefix:   /

nav_cms:
    resource: "@NavCMSBundle/Resources/config/routing/navigation.yml"
    prefix:   /cms

# Homepage
nav_cms_homepage:
    path:     /
    defaults: { _controller: NavCMSBundle:Default:index }

# Display a Page
nav_cms_page_display:
    path: /page/{id}
    defaults: { _controller: NavCMSBundle:Default:display }

nav_sendgrid:
    path: /sendgrid
    defaults: { _controller: NavSendGridBundle:Default:index }