# Login @See security.yml
login:
    path: /login
    defaults: { _controller: NavCMSBundle:Security:login }

# Login check
login_check:
    path: /login_check

# Logout
logout:
    path: /logout

# Usbstikje
nav_usbstikje:
    path: /usbstikje
    defaults: { _controller: NavCMSBundle:Usbstik:start }

# About
nav_about:
    path: /about
    defaults: { _controller: NavCMSBundle:About:index }

# Contact
nav_contact:
    path: /contact
    defaults: { _controller: NavCMSBundle:Contact:index }

# Test
nav_test:
    path: /test
    defaults: { _controller: NavCMSBundle:Test:index }

# Gists page
nav_gists:
    path: /gists
    defaults: { _controller: NavCMSBundle:Gists:index }


